export const artists = {
  hendrix: {
    cover: 'hendrix.png',
    id: 'hendrix',
    description: 'Alternative Rock',
    scope_of_work: '90s',
    price: 199.99,
    terms_of_ownership: 'Terms and services applied. NY, USA',
    owner: 'Rock Nation',
  },
  opera: {
    cover: 'opera.png',
    id: 'opera',
    description: 'Classic',
    scope_of_work: '50s',
    price: 99.99,
    terms_of_ownership: 'tems and services applied. Sweden',
    owner: 'Phantom of the Opera',
  },
  'rolling-stones': {
    cover: 'stones.png',
    id: 'rolling-stones',
    description: 'Punk Rock',
    scope_of_work: '70s',
    price: 129.99,
    terms_of_ownership: 'Terms and services applied. CA, USA',
    owner: 'Punk Rock Label',
  },
  u2: {
    cover: 'u2.png',
    id: 'u2',
    description: 'Rock',
    scope_of_work: '80s',
    price: 99.99,
    terms_of_ownership: 'Terms and services applied. Ireland',
    owner: 'Rock Label',
  },
};

export const albums = [
  {
    cover: 'u2.png',
    id: 'u2',
    description: 'Rock',
    scope_of_work: '80s',
    price: 99.99,
    terms_of_ownership: 'Terms and services applied. Ireland',
    owner: 'Rock Label',
  },
  {
    cover: 'hendrix.png',
    id: 'hendrix',
    description: 'Alternative Rock',
    scope_of_work: '90s',
    price: 199.99,
    terms_of_ownership: 'Terms and services applied. NY, USA',
    owner: 'Rock Nation',
  },
  {
    cover: 'stones.png',
    id: 'rolling-stones',
    description: 'Punk Rock',
    scope_of_work: '70s',
    price: 129.99,
    terms_of_ownership: 'Terms and services applied. CA, USA',
    owner: 'Punk Rock Label',
  },
  {
    cover: 'opera.png',
    id: 'opera',
    description: 'Classic',
    scope_of_work: '50s',
    price: 99.99,
    terms_of_ownership: 'tems and services applied. Sweden',
    owner: 'Phantom of the Opera',
  },
];
